#!/usr/bin/env bash

# Execute in script directory
cd "$(dirname "$0")"

# Set binary name depending on OS
if [[ "$OS" = "Windows_NT" ]]; then
    binary=corectl.exe
else
    binary=corectl
fi

go build -o ~/bin/$binary main.go
